task:
    name: Linux (GCC)
    container:
        image: gcc:latest
    env:
        DEBIAN_FRONTEND: noninteractive
    install_script: apt update && apt install --fix-missing -y git libgmp-dev libmpfr-dev libmpc-dev g++ cmake make wget valgrind && apt autoremove -y && apt autoclean -y
    compile_script:
        - export CI=true; export NPROC=2; sh build.sh
    tests_script: ${HOME}/.feral/bin/feral testdir tests && ${HOME}/.feral/bin/feral testdir tests --valgrind

# FreeBSD-13 uses Clang 11 -_- ; Too old!
# task:
#     name: FreeBSD
#     freebsd_instance:
#         image_family: freebsd-13-0
#     install_script: pkg install -y git gmp mpfr mpc cmake wget valgrind
#     compile_script:
#         - export CI=true; export NPROC=2; sh build.sh
#     # valgrind causes invalid KERN_PROC_PATHNAME to be set therefore manually FERAL_PATHS is set
#     tests_script: ${HOME}/.feral/bin/feral testdir tests

task:
    name: macOS Monterey Apple LLVM 13.0.0
    macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
    install_script: brew install git gmp mpfr libmpc cmake make
    compile_script:
        - export CI=true; export NPROC=$(sysctl -n hw.ncpu); sh build.sh
    tests_script: ${HOME}/.feral/bin/feral testdir tests