# LTO is disabled on ubuntu 14.04 and freebsd 10.4
# because clang 3.4 does work correctly with it
task:
    name: Ubuntu 14.04 gcc 4.8.4
    container:
        image: ubuntu:14.04
    install_script: apt-get update && apt-get install -y git libgmp-dev libmpfr-dev libmpc-dev g++ cmake make
    compile_script:
        - mkdir build && cd build && cmake .. && make -j$(nproc) install
        - git clone https://github.com/Feral-Lang/Feral-Std && cd Feral-Std && mkdir build && cd build && cmake .. && make -j$(nproc) install
    tests_script: feral testdir tests

task:
    name: Debian 8 gcc 6.5.0
    container:
        image: gcc:6
    env:
        CXX: g++
    install_script: apt update && apt install -y git libgmp-dev libmpfr-dev libmpc-dev cmake make
    compile_script:
        - mkdir build && cd build && cmake .. && make -j$(nproc) install
        - git clone https://github.com/Feral-Lang/Feral-Std && cd Feral-Std && mkdir build && cd build && cmake .. && make -j$(nproc) install
    tests_script: feral testdir tests

task:
    name: FreeBSD 10.4 clang 3.4.1
    freebsd_instance:
        image: freebsd-10-4-release-amd64
    env:
        SKIP_LTO: true
    install_script: pkg install -y git gmp mpfr mpc cmake
    compile_script:
        - mkdir build && cd build && cmake .. && make -j$(sysctl -n hw.ncpu) install
        - git clone https://github.com/Feral-Lang/Feral-Std && cd Feral-Std && mkdir build && cd build && cmake .. && make -j$(sysctl -n hw.ncpu) install
    tests_script: feral testdir tests

task:
    name: macOS Catalina Apple llvm 11.0.0
    osx_instance:
        image: catalina-base
    install_script: brew install git gmp mpfr libmpc cmake make
    compile_script:
        - mkdir build && cd build && cmake .. && make -j$(sysctl -n hw.ncpu) install
        - git clone https://github.com/Feral-Lang/Feral-Std && cd Feral-Std && mkdir build && cd build && cmake .. && make -j$(sysctl -n hw.ncpu) install
    tests_script: feral testdir tests