task:
    name: Ubuntu 20.04 gcc 9.3
    container:
        image: ubuntu:20.04
    env:
        DEBIAN_FRONTEND: noninteractive
    install_script: apt-get update && apt-get install -y git libgmp-dev libmpfr-dev libmpc-dev g++ cmake make wget valgrind
    compile_script:
        - export CI=true; sh build.sh
    tests_script: ${HOME}/.feral/bin/feral testdir tests && ${HOME}/.feral/bin/feral testdir tests --valgrind

task:
    name: Debian 8 gcc 6.5.0
    container:
        image: gcc:6
    env:
        CXX: g++
    install_script: apt update && apt install -y git libgmp-dev libmpfr-dev libmpc-dev cmake make valgrind
    compile_script:
        - export CI=true; sh build.sh
    tests_script: ${HOME}/.feral/bin/feral testdir tests && ${HOME}/.feral/bin/feral testdir tests --valgrind

task:
    name: FreeBSD 12.1
    freebsd_instance:
        image_family: freebsd-12-1
    install_script: pkg install -y git gmp mpfr mpc cmake wget valgrind
    compile_script:
        - export CI=true; sh build.sh
    # valgrind causes invalid KERN_PROC_PATHNAME to be set therefore manually FERAL_PATHS is set
    tests_script: ${HOME}/.feral/bin/feral testdir tests

task:
    name: macOS Catalina Apple llvm 11.0.0
    osx_instance:
        image: catalina-base
    install_script: brew install git gmp mpfr libmpc cmake make
    compile_script:
        - export CI=true; sh build.sh
    tests_script: ${HOME}/.feral/bin/feral testdir tests